# Config format schema number
format_version: 4

debug: True
data_path: '/mnt/andro/dynaGenData/traffic_gen_data'
use_cache: False

num_workers: 10
batch_size: 192
lr: 0.0003
weight_decay: 0.0004
device: 'gpu'
data_usage: 70508
pred_len: 90



