# Config format schema number
format_version: 4

debug: True
data_path: "./v2_data"
max_epoch: 50
num_workers: 0
batch_size: 16
lr: 0.0003
weight_decay: 0.0004
device: 'cpu'
phase: 'training'
data_usage: 0
model: "tt"
recache: True

min_agent: 8


# eval config
need_eval: True
eval_data_start_index: 0
eval_data_usage: 4
eval_batch_size: 1 # 2 frame * 50 map  will be plotted
eval_frequency: 1  # eval each epoch


