# Config format schema number
format_version: 4

debug: True
data_path: "/Users/fenglan/Downloads/waymo/dynamic_case"
#data_path: "/Users/fenglan/Downloads/waymo/v2_generated"
#data_path: "/Users/fenglan/Downloads/waymo/onemap"
max_epoch: 50
num_workers: 0
batch_size: 16
lr: 0.0003
weight_decay: 0.0004
device: 'cpu'
phase: 'training'
data_usage: 0
model: "tt"
recache: True
pred_len: 45

# eval config
need_eval: True
eval_data_start_index: 166
eval_data_usage: 1
eval_batch_size: 16
eval_frequency: 1


